### ISSUE TITLE
Review time-series analysis values

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/ghgc-docs#62]
# Description
The dashboard wasn't passing the `nodata` value to the `/statistics` endpoint when creating the time-series chart. This was causing the time-series to be incorrect because the calculation was also including the nodata values as real values.

Related issue and PR here:
https://github.com/US-GHG-Center/ghgc-architecture/issues/158
https://github.com/US-GHG-Center/veda-config-ghg/pull/324

It has been fixed in the dashboard, but we need to check if the issue also appears in the notebooks. And if so, fix those.

# AC
- [x] Found + fixed analysis nodata issue

**Comment by j08lue** [comment]
> The dashboard wasn't passing the `nodata` value to the `/statistics` endpoint when creating the time-series chart

Just for the record - the original issue is that the data files do not have the `nodata` value set in their metadata, which they should. 😉 Maybe we should ticket fixing that, actually?

I agree that we in the meantime should update the docs with this workaround of passing in the nodata value manually.

**Comment by slesaad** [comment]
yep, already ticketed here - https://github.com/US-GHG-Center/ghgc-data/issues/9

**Comment by jerikac** [comment]
Reingested all data and nodata values are showing properly. Next: ingest items and see if there issues with visualizations. A new MiCASA dataset is available in the S3 bucket that now includes NAN -- Vishal to investigate whether this causes statistics issues...

**Comment by SwordSaintLancelot** [comment]
The datasets have been updated with `nodata` value as `-9999` in [this](https://github.com/US-GHG-Center/ghgc-docs/pull/84) PR except the MiCASA dataset as the POCs do not want to add `NaN` as `nodata` value instead of '-9999`. I have checked in the `cog/statistics` endpoint from raster API that the `nodata` value retrieved from the COGs is indeed `-9999` for the updated data.

The next step will be to ingest the updated data in dev STAC and visualize them to make sure there are no discrepancies in visualization.
